"use client";

import { useState, useEffect, useCallback } from "react";
import SyntaxHighlighter from "react-syntax-highlighter";
import ReactMarkdown from "react-markdown";
import DependencyGraph from "./DependencyGraph";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";

type TabId = "dashboard" | "query" | "dependencies" | "document" | "patterns" | "explain-snippet" | "business-logic";

type HealthDashboardData = {
  total_chunks: number;
  total_files: number;
  total_loc: number;
  top_files: { file: string; chunks?: number; loc: number }[];
  languages: { name: string; files: number; percentage: number }[];
  patterns_summary: { pattern: string; count: number }[];
  health_score: number;
  health_notes: string[];
  latency_ms?: number;
  computed_at?: string;
};

type SourceItem = {
  file: string;
  path?: string;
  paragraph: string;
  start_line: number;
  end_line: number;
  snippet: string;
  score?: number;
  source?: string;
};

const TABS: { id: TabId; label: string }[] = [
  { id: "dashboard", label: "🏥 Dashboard" },
  { id: "query", label: "🔍 Ask" },
  { id: "dependencies", label: "🔗 Dependencies" },
  { id: "document", label: "📄 Docs" },
  { id: "patterns", label: "🔎 Patterns" },
  { id: "explain-snippet", label: "🔬 Snippet" },
  { id: "business-logic", label: "💼 Business Logic" },
];

const EXAMPLE_QUERIES: Record<TabId, string[]> = {
  dashboard: [],
  query: [
    "Where is the main entry point of this program?",
    "Find all file I/O operations",
    "Show me error handling patterns in this codebase",
    "What does the PROCEDURE DIVISION do?",
  ],
  dependencies: [
    "What are all the PERFORM relationships in the main procedure?",
    "What does MAIN-SECTION call?",
    "What calls the STOP-RUN paragraph?",
    "Show the call graph for this program",
  ],
  document: [
    "Generate docs for the main entry point",
    "Document the file I/O section",
    "Explain the PROCEDURE DIVISION",
  ],
  patterns: [
    "Find all OPEN READ WRITE operations",
    "Show all error handling patterns",
    "Find all PERFORM statements",
  ],
  "explain-snippet": [],
  "business-logic": [
    "Extract business rules from file I/O section",
    "What business process does error handling implement?",
    "Explain the business logic of the main procedure",
  ],
};

const TAB_DISPLAY_NAMES: Record<TabId, string> = {
  dashboard: "Dashboard",
  query: "Ask a Question",
  dependencies: "Dependencies",
  document: "Documentation",
  patterns: "Patterns",
  "explain-snippet": "Explain Snippet",
  "business-logic": "Business Logic",
};

const exportToMarkdown = (
  query: string,
  answer: string,
  sources: SourceItem[],
  tabName: string
) => {
  const date = new Date().toLocaleString();
  let content = `# LegacyLens Analysis Report\n\n`;
  content += `**Generated:** ${date}\n`;
  content += `**Query:** ${query}\n`;
  content += `**Tab:** ${tabName}\n\n---\n\n`;
  content += `## Answer\n\n${answer}\n\n`;
  if (sources.length > 0) {
    content += `---\n\n## Sources\n\n`;
    sources.forEach((s) => {
      content += `### ${s.file} — Lines ${s.start_line}–${s.end_line}\n`;
      content += `**Paragraph:** ${s.paragraph}\n`;
      content += `**Confidence:** ${(s.score ?? 0).toFixed(1)}% match\n\n`;
      content += `\`\`\`cobol\n${s.snippet}\n\`\`\`\n\n`;
    });
  }
  content += `---\n*Generated by LegacyLens — RAG-powered COBOL codebase analysis*\n*https://legacy-lens-nine.vercel.app*`;

  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `legacylens-report-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
};

const PLACEHOLDERS: Record<TabId, string> = {
  dashboard: "",
  query: "Ask about the COBOL codebase...",
  dependencies: "Ask about what calls what (e.g. What does MAIN-SECTION call?)",
  document: "Enter a paragraph or file name to generate documentation for",
  patterns: "Search for a code pattern (e.g. OPEN READ WRITE for file I/O)",
  "explain-snippet": "",
  "business-logic": "Describe a section to extract business rules from (e.g. interest calculation, file processing)",
};

const EXPLAIN_SNIPPET_EXAMPLES = [
  "MOVE ZEROS TO WS-COUNTER.",
  "PERFORM UNTIL WS-EOF = 'Y' READ INPUT-FILE INTO WS-RECORD AT END MOVE 'Y' TO WS-EOF END-READ END-PERFORM.",
  "IF WS-AMOUNT > 1000 MOVE 'HIGH' TO WS-CATEGORY ELSE MOVE 'LOW' TO WS-CATEGORY END-IF.",
];

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
  sources?: SourceItem[];
  latencyMs?: number;
};

const FALLBACK_DASHBOARD: HealthDashboardData = {
  total_chunks: 16406,
  total_files: 433,
  total_loc: 354916,
  top_files: [
    { file: "nist85.cbl", chunks: 847, loc: 25000 },
    { file: "fileio.c", chunks: 312, loc: 8500 },
    { file: "common.h", chunks: 201, loc: 5200 },
    { file: "cobc.h", chunks: 189, loc: 4800 },
    { file: "typeck.c", chunks: 156, loc: 4100 },
  ],
  languages: [{ name: "COBOL", files: 433, percentage: 100 }],
  patterns_summary: [
    { pattern: "File I/O Operations", count: 2847 },
    { pattern: "Error Handling", count: 1203 },
    { pattern: "PERFORM Statements", count: 3412 },
    { pattern: "Data Division", count: 891 },
    { pattern: "MOVE Statements", count: 4521 },
  ],
  health_score: 72,
  health_notes: [
    "Large codebase with complex paragraph dependencies",
    "High PERFORM statement density indicates deep call chains",
    "Error handling present but inconsistent across files",
  ],
};

export default function Home() {
  const [activeTab, setActiveTab] = useState<TabId>("dashboard");
  const [sessionId] = useState(() => Math.random().toString(36).substring(2, 15));
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [queryInput, setQueryInput] = useState("");
  const [docInput, setDocInput] = useState("");
  const [patternInput, setPatternInput] = useState("OPEN READ WRITE");
  const [snippetInput, setSnippetInput] = useState("");
  const [snippetExplanation, setSnippetExplanation] = useState<string | null>(null);
  const [snippetLatencyMs, setSnippetLatencyMs] = useState<number | null>(null);
  const [businessLogicInput, setBusinessLogicInput] = useState("");
  const [answer, setAnswer] = useState("");
  const [sources, setSources] = useState<SourceItem[]>([]);
  const [callGraph, setCallGraph] = useState<{ caller: string; callee: string; file: string; line: number }[]>([]);
  const [depsGraph, setDepsGraph] = useState<{ nodes: { id: string; type: string; file: string }[]; edges: { source: string; target: string; type: string }[] }>({ nodes: [], edges: [] });
  const [depsViewMode, setDepsViewMode] = useState<"list" | "graph">("list");
  const [selectedNodeAnswer, setSelectedNodeAnswer] = useState<string | null>(null);
  const [selectedNodeLoading, setSelectedNodeLoading] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [latencyMs, setLatencyMs] = useState<number | null>(null);
  const [expandedFile, setExpandedFile] = useState<{ path: string; content: string; line_count: number } | null>(null);
  const [expandedSourceIdx, setExpandedSourceIdx] = useState<number | null>(null);
  const [expandedSourcesForMessage, setExpandedSourcesForMessage] = useState<number | null>(null);
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const [expandedChatSource, setExpandedChatSource] = useState<{ messageIdx: number; sourceIdx: number } | null>(null);
  const [expandedMessageIdx, setExpandedMessageIdx] = useState<number | null>(null);
  const [dashboardData, setDashboardData] = useState<HealthDashboardData | null>(null);
  const [dashboardLoading, setDashboardLoading] = useState(true);

  const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

  useEffect(() => {
    if (activeTab === "dashboard") {
      setDashboardLoading(true);
      fetch(`${apiUrl}/health-dashboard`)
        .then((r) => r.json())
        .then((d) => setDashboardData(d))
        .catch(() => setDashboardData(FALLBACK_DASHBOARD))
        .finally(() => setDashboardLoading(false));
    }
  }, [activeTab, apiUrl]);

  const askedQuestions = new Set(chatHistory.filter((m) => m.role === "user").map((m) => m.content.trim().toLowerCase()));
  const suggestedQueries = EXAMPLE_QUERIES[activeTab].filter(
    (q) => !askedQuestions.has(q.trim().toLowerCase())
  );

  const handleDepsNodeClick = useCallback(
    async (nodeName: string) => {
      setSelectedNodeLoading(true);
      setSelectedNodeAnswer(null);
      try {
        const res = await fetch(`${apiUrl}/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            question: `Explain the ${nodeName} paragraph`,
            session_id: "deps-graph",
          }),
        });
        if (!res.ok) throw new Error("Query failed");
        const data = await res.json();
        setSelectedNodeAnswer(data.answer);
      } catch {
        setSelectedNodeAnswer("Failed to load explanation.");
      } finally {
        setSelectedNodeLoading(false);
      }
    },
    [apiUrl]
  );

  const formatLineRange = (start: number, end: number) => {
    if (end > start && end - start > 1000) return `L${start}–${end} (large range)`;
    return `L${start}–${end}`;
  };

  const getInput = () => {
    if (activeTab === "dashboard") return "";
    if (activeTab === "query") return queryInput;
    if (activeTab === "dependencies") return queryInput;
    if (activeTab === "document") return docInput;
    if (activeTab === "explain-snippet") return snippetInput;
    if (activeTab === "business-logic") return businessLogicInput;
    return patternInput;
  };

  const setInput = (v: string) => {
    if (activeTab === "dashboard") return;
    if (activeTab === "query" || activeTab === "dependencies") setQueryInput(v);
    else if (activeTab === "document") setDocInput(v);
    else if (activeTab === "explain-snippet") setSnippetInput(v);
    else if (activeTab === "business-logic") setBusinessLogicInput(v);
    else setPatternInput(v);
  };

  const canSubmit = () => {
    if (activeTab === "dashboard") return false;
    if (activeTab === "query" || activeTab === "dependencies") return queryInput.trim();
    if (activeTab === "document") return docInput.trim();
    if (activeTab === "explain-snippet") return snippetInput.trim();
    if (activeTab === "business-logic") return businessLogicInput.trim();
    return patternInput.trim();
  };

  const handleClearConversation = async () => {
    try {
      await fetch(`${apiUrl}/clear-history`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ session_id: sessionId }),
      });
      setChatHistory([]);
      setExpandedSourcesForMessage(null);
      setExpandedChatSource(null);
      setExpandedMessageIdx(null);
    } catch {
      setChatHistory([]);
      setExpandedMessageIdx(null);
    }
  };

  const handleSubmit = async (overrideQuestion?: string) => {
    const canSend = activeTab === "query"
      ? (overrideQuestion ? overrideQuestion.trim() : queryInput.trim())
      : canSubmit();
    if (!canSend) return;
    setLoading(true);
    setError(null);
    if (activeTab !== "query" && activeTab !== "explain-snippet") {
      setAnswer("");
      setSources([]);
      setCallGraph([]);
      setLatencyMs(null);
      setSourcesOpen(false);
    }
    setExpandedFile(null);
    setExpandedSourceIdx(null);

    try {
      if (activeTab === "query") {
        const question = (overrideQuestion ?? queryInput).trim();
        setChatHistory((prev) => {
          const last = prev[prev.length - 1];
          if (last?.role === "user" && last.content === question) return prev;
          return [...prev, { role: "user" as const, content: question }];
        });
        if (!overrideQuestion) setQueryInput("");
        const res = await fetch(`${apiUrl}/query`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ question, session_id: sessionId }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setChatHistory((prev) => {
          const last = prev[prev.length - 1];
          if (last?.role === "assistant") return prev;
          return [
            ...prev,
            {
              role: "assistant" as const,
              content: data.answer,
              sources: data.sources || [],
              latencyMs: data.latency_ms ?? undefined,
            },
          ];
        });
      } else if (activeTab === "dependencies") {
        const res = await fetch(`${apiUrl}/dependencies`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ question: queryInput.trim() || undefined }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setAnswer(data.answer);
        setSources(data.sources || []);
        setCallGraph(data.call_graph || []);
        setDepsGraph(data.graph || { nodes: [], edges: [] });
        setLatencyMs(data.latency_ms ?? null);
        setSelectedNodeAnswer(null);
      } else if (activeTab === "document") {
        const res = await fetch(`${apiUrl}/document`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ paragraph: docInput.trim(), file_name: docInput.trim() }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setAnswer(data.documentation);
        setSources(data.sources || []);
        setLatencyMs(data.latency_ms ?? null);
      } else if (activeTab === "explain-snippet") {
        setSnippetExplanation(null);
        setSnippetLatencyMs(null);
        const res = await fetch(`${apiUrl}/explain-snippet`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ code: snippetInput.trim() }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setSnippetExplanation(data.explanation);
        setSnippetLatencyMs(data.latency_ms ?? null);
      } else if (activeTab === "business-logic") {
        const res = await fetch(`${apiUrl}/business-logic`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ question: businessLogicInput.trim() }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setAnswer(data.business_logic);
        setSources(data.sources || []);
        setLatencyMs(data.latency_ms ?? null);
      } else {
        const res = await fetch(`${apiUrl}/patterns`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ keyword: patternInput.trim() }),
        });
        if (!res.ok) throw new Error(`API error: ${res.status}`);
        const data = await res.json();
        setAnswer(data.answer);
        setSources(data.sources || []);
        setLatencyMs(data.latency_ms ?? null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Request failed");
      if (activeTab === "query") {
        setChatHistory((prev) => {
          const last = prev[prev.length - 1];
          if (last?.role === "user") return prev.slice(0, -1);
          return prev;
        });
      }
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleViewFullFile = async (sourcePath: string, idx: number) => {
    if (!sourcePath) return;
    if (expandedSourceIdx === idx && expandedFile) {
      setExpandedFile(null);
      setExpandedSourceIdx(null);
      return;
    }
    try {
      const res = await fetch(`${apiUrl}/file?path=${encodeURIComponent(sourcePath)}`);
      const data = await res.json();
      if (data.error || !res.ok) {
        setError("Full file preview is not available in production. Clone the repo locally to use this feature.");
        return;
      }
      setError(null);
      setExpandedFile({ path: data.path, content: data.content, line_count: data.line_count });
      setExpandedSourceIdx(idx);
    } catch {
      setError("Full file preview is not available in production. Clone the repo locally to use this feature.");
    }
  };

  const getButtonLabel = () => {
    if (loading) return "Loading...";
    if (activeTab === "query") return "Ask";
    if (activeTab === "dependencies") return "Search";
    if (activeTab === "document") return "Generate";
    if (activeTab === "explain-snippet") return "Explain";
    if (activeTab === "business-logic") return "Extract";
    return "Search";
  };

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      <main className="overflow-auto">
        <div className="mx-auto max-w-3xl px-6 py-16">
          <h1 className="mb-2 text-3xl font-bold tracking-tight">Legacy Lens</h1>
        <p className="mb-10 text-gray-400">
          Query the COBOL codebase in natural language
        </p>

        {/* Tab bar - scrollable on smaller screens, all 5 tabs */}
        <div className="flex overflow-x-auto gap-1 mb-4 border-b border-gray-700 pb-0">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`whitespace-nowrap px-4 py-2 text-sm font-medium transition shrink-0 ${
                activeTab === tab.id
                  ? "border-b-2 border-blue-500 text-blue-400"
                  : "text-gray-400 hover:text-gray-200"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
        {activeTab === "query" && (
          <div className="mb-6">
            <button
              onClick={handleClearConversation}
              className="rounded border border-gray-600 bg-gray-800 px-3 py-1.5 text-sm text-gray-300 hover:bg-gray-700"
            >
              🗑 Clear conversation
            </button>
          </div>
        )}

        {/* Dashboard tab */}
        {activeTab === "dashboard" && (
          <div className="mb-8 space-y-8">
            {dashboardLoading ? (
              <div className="flex items-center justify-center py-16">
                <div className="h-10 w-10 animate-spin rounded-full border-2 border-emerald-500 border-t-transparent" />
              </div>
            ) : (
              <>
                {(() => {
                  const d = dashboardData || FALLBACK_DASHBOARD;
                  const maxLoc = Math.max(...d.top_files.map((f) => f.loc), 1);
                  return (
                    <>
                      {/* Row 1 — 3 stat cards */}
                      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                        <div className="rounded-xl bg-gray-800 p-6">
                          <div className="text-3xl">📁</div>
                          <div className="mt-1 text-2xl font-bold text-gray-100">
                            {d.total_files.toLocaleString()}
                          </div>
                          <div className="mt-1 text-sm text-gray-400">Total Files</div>
                        </div>
                        <div className="rounded-xl bg-gray-800 p-6">
                          <div className="text-3xl">📝</div>
                          <div className="mt-1 text-2xl font-bold text-gray-100">
                            {d.total_loc.toLocaleString()}
                          </div>
                          <div className="mt-1 text-sm text-gray-400">Lines of Code</div>
                        </div>
                        <div className="rounded-xl bg-gray-800 p-6">
                          <div className="text-3xl">🧩</div>
                          <div className="mt-1 text-2xl font-bold text-gray-100">
                            {d.total_chunks.toLocaleString()}
                          </div>
                          <div className="mt-1 text-sm text-gray-400">Indexed Chunks</div>
                        </div>
                      </div>
                      {d.computed_at && (
                        <p className="mt-2 text-center text-xs text-gray-500">
                          Last computed: {new Date(d.computed_at).toLocaleString()}
                        </p>
                      )}

                      {/* Row 2 — Health Score */}
                      <div className="rounded-xl bg-gray-800 p-6">
                        <h2 className="mb-4 text-center text-lg font-semibold text-gray-200">
                          Codebase Health Score: {d.health_score}/100
                        </h2>
                        <div className="mb-4 h-3 overflow-hidden rounded-full bg-gray-700">
                          <div
                            className={`h-full rounded-full transition-all ${
                              d.health_score >= 80
                                ? "bg-green-500"
                                : d.health_score >= 60
                                  ? "bg-yellow-500"
                                  : "bg-red-500"
                            }`}
                            style={{ width: `${d.health_score}%` }}
                          />
                        </div>
                        <div className="prose prose-invert prose-sm max-w-none text-gray-400">
                          <ReactMarkdown>
                            {d.health_notes.map((n) => `- ${n}`).join("\n")}
                          </ReactMarkdown>
                        </div>
                      </div>

                      {/* Row 3 — Two columns */}
                      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                        <div className="rounded-xl bg-gray-800 p-6">
                          <h3 className="mb-4 font-semibold text-gray-200">
                            📊 Top Files by Complexity
                          </h3>
                          <div className="space-y-3">
                            {d.top_files.map((f) => (
                              <div key={f.file} className="flex items-center gap-3">
                                <div className="min-w-0 flex-1">
                                  <div className="truncate text-sm text-gray-300">{f.file}</div>
                                  <div className="flex items-center gap-2">
                                    <div className="h-2 flex-1 overflow-hidden rounded bg-gray-700">
                                      <div
                                        className="h-full rounded bg-emerald-600"
                                        style={{ width: `${(f.loc / maxLoc) * 100}%` }}
                                      />
                                    </div>
                                    <span className="shrink-0 text-xs text-gray-500">
                                      {f.loc.toLocaleString()} loc
                                    </span>
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                        <div className="rounded-xl bg-gray-800 p-6">
                          <h3 className="mb-4 font-semibold text-gray-200">
                            🔍 Pattern Distribution
                          </h3>
                          <div className="space-y-3">
                            {d.patterns_summary.map((p) => {
                              const maxCount = Math.max(...d.patterns_summary.map((x) => x.count), 1);
                              const percentage = Math.round((p.count / maxCount) * 100);
                              return (
                                <div key={p.pattern} className="flex items-center gap-3">
                                  <div className="min-w-0 flex-1">
                                    <div className="flex justify-between text-sm">
                                      <span className="text-gray-300">{p.pattern}</span>
                                      <span className="text-gray-500">
                                        {p.count.toLocaleString()} ({percentage}%)
                                      </span>
                                    </div>
                                    <div className="mt-1 h-2 overflow-hidden rounded bg-gray-700">
                                      <div
                                        className="h-full rounded bg-blue-600"
                                        style={{ width: `${percentage}%` }}
                                      />
                                    </div>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      </div>

                      {/* Row 4 — Bottom banner */}
                      <div className="rounded-lg border border-gray-700 bg-gray-900/50 px-4 py-3 text-center text-sm text-gray-400">
                        ⚡ Powered by Pinecone + GPT-4o-mini — {d.total_chunks.toLocaleString()} vectors
                        indexed across {d.total_files.toLocaleString()} COBOL files
                      </div>
                    </>
                  );
                })()}
              </>
            )}
          </div>
        )}

        {/* Chat history (Ask a Question tab only) */}
        {activeTab === "query" && chatHistory.length > 0 && (
          <div className="mb-6 space-y-4">
            {chatHistory.map((msg, msgIdx) => {
              const isExpanded = expandedMessageIdx === msgIdx;
              const contentPreviewLen = 180;
              const showExpand = msg.role === "assistant" && msg.content.length > contentPreviewLen;
              const displayContent = showExpand && !isExpanded
                ? msg.content.slice(0, contentPreviewLen) + (msg.content.length > contentPreviewLen ? "…" : "")
                : msg.content;
              const prevUserMsg = chatHistory.slice(0, msgIdx).reverse().find((m) => m.role === "user");

              return (
                <div
                  key={msgIdx}
                  className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  <div
                    className={`relative max-w-[85%] rounded-lg px-4 py-3 ${
                      msg.role === "user"
                        ? "bg-blue-600 text-white"
                        : "bg-gray-800 text-gray-200"
                    }`}
                  >
                    {msg.role === "assistant" && msg.content && (
                      <button
                        onClick={() =>
                          exportToMarkdown(
                            prevUserMsg?.content ?? "Query",
                            msg.content,
                            msg.sources ?? [],
                            TAB_DISPLAY_NAMES.query
                          )
                        }
                        className="absolute right-2 top-2 rounded bg-gray-700 px-3 py-1 text-xs text-white hover:bg-gray-600"
                      >
                        📥 Export
                      </button>
                    )}
                    <div className="prose prose-invert prose-sm max-w-none text-gray-300">
                      <ReactMarkdown>{displayContent}</ReactMarkdown>
                    </div>
                    {showExpand && (
                      <button
                        onClick={() => setExpandedMessageIdx(isExpanded ? null : msgIdx)}
                        className="mt-1 text-xs text-emerald-400 hover:text-emerald-300"
                      >
                        {isExpanded ? "Show less" : "Show more"}
                      </button>
                    )}
                    {msg.role === "assistant" && msg.latencyMs != null && (
                      <div className="mt-2 text-xs text-gray-500">⚡ {msg.latencyMs}ms</div>
                    )}
                    {msg.role === "assistant" && msg.sources && msg.sources.length > 0 && (
                      <div className="mt-3">
                        <button
                          onClick={() =>
                            setExpandedSourcesForMessage(
                              expandedSourcesForMessage === msgIdx ? null : msgIdx
                            )
                          }
                          className="mt-2 cursor-pointer text-xs text-gray-500 hover:text-gray-300"
                        >
                          {expandedSourcesForMessage === msgIdx
                            ? `▼ ${msg.sources.length} source${msg.sources.length !== 1 ? "s" : ""} retrieved · click to collapse`
                            : `▶ ${msg.sources.length} source${msg.sources.length !== 1 ? "s" : ""} retrieved · click to expand`}
                        </button>
                        {expandedSourcesForMessage === msgIdx && (
                          <div className="mt-3 space-y-2">
                            <p className="text-xs text-gray-400 mb-2">SOURCES ({msg.sources.length})</p>
                            {msg.sources.map((s, sIdx) => (
                              <div
                                key={sIdx}
                                className="rounded-lg border border-gray-700 bg-gray-900/80 p-3"
                              >
                                <div className="mb-2 grid grid-cols-[1fr_auto_auto] gap-2 items-center text-xs sm:flex sm:flex-wrap">
                                  <span className="font-medium text-emerald-400 truncate" title={s.file}>
                                    {s.file}
                                  </span>
                                  <span className="text-gray-400">
                                    {formatLineRange(s.start_line, s.end_line)}
                                  </span>
                                  {s.score != null && (
                                    <span
                                      className={`shrink-0 px-2 py-0.5 rounded-full font-medium ${
                                        s.score >= 55 ? "bg-green-900 text-green-300" :
                                        s.score >= 40 ? "bg-yellow-900 text-yellow-300" :
                                        "bg-red-900 text-red-300"
                                      }`}
                                    >
                                      {typeof s.score === "number" ? s.score.toFixed(1) : s.score}%
                                    </span>
                                  )}
                                </div>
                                <SyntaxHighlighter
                                  language="cobol"
                                  style={vscDarkPlus}
                                  customStyle={{ borderRadius: "6px", fontSize: "12px" }}
                                  PreTag="div"
                                  codeTagProps={{ style: { fontFamily: "var(--font-geist-mono)" } }}
                                >
                                  {s.snippet}
                                </SyntaxHighlighter>
                                {(s.source || s.path) && (
                                  <button
                                    onClick={() => {
                                      if (
                                        expandedChatSource?.messageIdx === msgIdx &&
                                        expandedChatSource?.sourceIdx === sIdx
                                      ) {
                                        setExpandedChatSource(null);
                                        setExpandedFile(null);
                                        return;
                                      }
                                      setExpandedChatSource({ messageIdx: msgIdx, sourceIdx: sIdx });
                                      fetch(`${apiUrl}/file?path=${encodeURIComponent(s.source || s.path || "")}`)
                                        .then((r) => r.json())
                                        .then((d) => {
                                          if (d.error || !d.content) return;
                                          setExpandedFile({ path: d.path, content: d.content, line_count: d.line_count });
                                        });
                                    }}
                                    className="mt-2 rounded border border-gray-600 bg-gray-800 px-2 py-1 text-xs text-gray-300 hover:bg-gray-700"
                                  >
                                    {expandedChatSource?.messageIdx === msgIdx &&
                                    expandedChatSource?.sourceIdx === sIdx &&
                                    expandedFile
                                      ? "Collapse"
                                      : "View full file"}
                                  </button>
                                )}
                                {expandedChatSource?.messageIdx === msgIdx &&
                                  expandedChatSource?.sourceIdx === sIdx &&
                                  expandedFile && (
                                    <div className="mt-3 rounded border border-gray-700 bg-gray-950 p-3">
                                      <div className="mb-1 text-xs text-gray-400">
                                        {expandedFile.path} ({expandedFile.line_count} lines)
                                      </div>
                                      <SyntaxHighlighter
                                        language="cobol"
                                        style={vscDarkPlus}
                                        customStyle={{ borderRadius: "6px", fontSize: "12px", maxHeight: "300px" }}
                                        PreTag="div"
                                        showLineNumbers
                                      >
                                        {expandedFile.content}
                                      </SyntaxHighlighter>
                                    </div>
                                  )}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Input area (hidden on dashboard and explain-snippet) */}
        {activeTab !== "dashboard" && activeTab !== "explain-snippet" && (
        <div className="mb-6">
          <div className="flex gap-2">
            <input
              type="text"
              value={getInput()}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={PLACEHOLDERS[activeTab]}
              className="flex-1 rounded-lg border border-gray-700 bg-gray-900 px-4 py-3 text-gray-100 placeholder-gray-500 focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500"
              disabled={loading}
            />
            <button
              onClick={() => handleSubmit()}
              disabled={loading || !canSubmit()}
              className="rounded-lg bg-emerald-600 px-6 py-3 font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {getButtonLabel()}
            </button>
          </div>
        </div>

        )}

        {/* Explain Snippet tab: two panels */}
        {activeTab === "explain-snippet" && (
          <div className="mb-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
            <div className="space-y-3">
              <label className="block text-sm font-medium text-gray-400">Paste COBOL code here</label>
              <textarea
                value={snippetInput}
                onChange={(e) => setSnippetInput(e.target.value)}
                placeholder="Paste any COBOL paragraph, section, or snippet here..."
                className="min-h-[300px] w-full rounded-lg border border-gray-700 bg-gray-800 px-4 py-3 font-mono text-sm text-green-400 placeholder-gray-500 focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                disabled={loading}
              />
              <button
                onClick={() => handleSubmit()}
                disabled={loading || !snippetInput.trim()}
                className="rounded-lg bg-emerald-600 px-6 py-3 font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {getButtonLabel()}
              </button>
              <div className="flex flex-wrap gap-2 pt-2">
                {EXPLAIN_SNIPPET_EXAMPLES.map((snippet, i) => (
                  <button
                    key={i}
                    onClick={() => setSnippetInput(snippet)}
                    className="rounded-full border border-gray-600 bg-gray-900 px-4 py-2 text-xs font-mono text-gray-300 transition hover:border-emerald-600 hover:text-emerald-400"
                  >
                    {snippet.length > 50 ? snippet.slice(0, 47) + "…" : snippet}
                  </button>
                ))}
              </div>
            </div>
            <div className="relative rounded-lg border border-gray-800 bg-gray-900/50 p-6">
              <div className="mb-3 flex items-center justify-between">
                <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-400">
                  Explanation
                </h2>
                {snippetExplanation && (
                  <button
                    onClick={() =>
                      exportToMarkdown(
                        snippetInput,
                        snippetExplanation,
                        [],
                        TAB_DISPLAY_NAMES["explain-snippet"]
                      )
                    }
                    className="rounded bg-gray-700 px-3 py-1 text-xs text-white hover:bg-gray-600"
                  >
                    📥 Export
                  </button>
                )}
              </div>
              {loading ? (
                <div className="flex items-center gap-2 py-8">
                  <div className="h-6 w-6 animate-spin rounded-full border-2 border-emerald-500 border-t-transparent" />
                  <span className="text-gray-400">Analyzing code...</span>
                </div>
              ) : snippetExplanation ? (
                <>
                  <div className="prose prose-invert prose-sm max-w-none text-gray-300">
                    <ReactMarkdown>{snippetExplanation}</ReactMarkdown>
                  </div>
                  {snippetLatencyMs != null && (
                    <div className="mt-4 text-sm text-gray-500">
                      ⚡ Response time: {snippetLatencyMs}ms
                    </div>
                  )}
                </>
              ) : (
                <p className="text-gray-500">
                  Paste any COBOL code on the left and click Explain to get an instant plain-English breakdown.
                </p>
              )}
            </div>
          </div>
        )}

        {/* Example chips - hide ones already asked (hidden on dashboard and explain-snippet) */}
        {activeTab !== "dashboard" && activeTab !== "explain-snippet" && (
        <div className="mb-8 flex flex-wrap gap-2">
          {(suggestedQueries.length > 0 ? suggestedQueries : EXAMPLE_QUERIES[activeTab]).map((q) => (
            <button
              key={q}
              onClick={() =>
                activeTab === "query"
                  ? handleSubmit(q)
                  : setInput(q)
              }
              className="rounded-full border border-gray-600 bg-gray-900 px-4 py-2 text-sm text-gray-300 transition hover:border-emerald-600 hover:text-emerald-400"
            >
              {q}
            </button>
          ))}
        </div>
        )}

        {error && (
          <div className="mb-6 rounded-lg border border-red-800 bg-red-950/30 px-4 py-3 text-red-400">
            {error}
          </div>
        )}

        {/* Dependencies tab: List or Graph view */}
        {activeTab === "dependencies" && (answer || callGraph.length > 0 || depsGraph.nodes.length > 0) && (
          <div className="mb-8 space-y-4">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setDepsViewMode("list")}
                className={`rounded px-3 py-1.5 text-sm ${
                  depsViewMode === "list"
                    ? "bg-gray-700 text-white"
                    : "bg-gray-800 text-gray-400 hover:text-gray-200"
                }`}
              >
                📋 List View
              </button>
              <button
                onClick={() => setDepsViewMode("graph")}
                className={`rounded px-3 py-1.5 text-sm ${
                  depsViewMode === "graph"
                    ? "bg-gray-700 text-white"
                    : "bg-gray-800 text-gray-400 hover:text-gray-200"
                }`}
              >
                🕸 Graph View
              </button>
            </div>

            {depsViewMode === "list" ? (
              <>
                {callGraph.length > 0 && (
                  <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-6">
                    <h2 className="mb-3 text-sm font-semibold uppercase tracking-wider text-gray-400">
                      Call Graph
                    </h2>
                    <div className="space-y-1 font-mono text-sm text-gray-300">
                      {callGraph.map((cg, i) => (
                        <div key={i}>
                          {cg.caller} → {cg.callee} ({cg.file}:{cg.line})
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </>
            ) : (
              <div className="rounded-lg border border-gray-800 bg-gray-900 p-4">
                <DependencyGraph
                  nodes={depsGraph.nodes}
                  edges={depsGraph.edges}
                  onNodeClick={handleDepsNodeClick}
                  width={800}
                  height={600}
                />
                {selectedNodeLoading && (
                  <div className="mt-4 flex items-center gap-2 text-sm text-gray-400">
                    <div className="h-4 w-4 animate-spin rounded-full border-2 border-emerald-500 border-t-transparent" />
                    Loading explanation...
                  </div>
                )}
                {selectedNodeAnswer && !selectedNodeLoading && (
                  <div className="relative mt-4 rounded-lg border border-gray-700 bg-gray-800/50 p-4">
                    <div className="mb-2 flex items-center justify-between">
                      <h3 className="text-sm font-semibold text-gray-300">
                        Paragraph explanation
                      </h3>
                      <button
                        onClick={() =>
                          exportToMarkdown(
                            "Explain the paragraph (from graph node click)",
                            selectedNodeAnswer,
                            [],
                            TAB_DISPLAY_NAMES.dependencies
                          )
                        }
                        className="rounded bg-gray-700 px-3 py-1 text-xs text-white hover:bg-gray-600"
                      >
                        📥 Export
                      </button>
                    </div>
                    <div className="prose prose-invert prose-sm max-w-none text-sm text-gray-300">
                      <ReactMarkdown>{selectedNodeAnswer}</ReactMarkdown>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* Answer (non-query, non-explain-snippet tabs only) */}
        {activeTab !== "query" && activeTab !== "explain-snippet" && answer && (
          <div className="relative mb-8 rounded-lg border border-gray-800 bg-gray-900/50 p-6">
            <div className="mb-3 flex items-center justify-between">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-400">
                {activeTab === "document" ? "Documentation" : activeTab === "business-logic" ? "Business Logic" : "Answer"}
              </h2>
              <button
                onClick={() =>
                  exportToMarkdown(
                    activeTab === "dependencies" ? queryInput : activeTab === "document" ? docInput : activeTab === "patterns" ? patternInput : businessLogicInput,
                    answer,
                    sources,
                    TAB_DISPLAY_NAMES[activeTab]
                  )
                }
                className="rounded bg-gray-700 px-3 py-1 text-xs text-white hover:bg-gray-600"
              >
                📥 Export
              </button>
            </div>
            <div className="prose prose-invert prose-sm max-w-none text-gray-300">
              <ReactMarkdown>{answer}</ReactMarkdown>
            </div>
            {latencyMs != null && (
              <div className="mt-3 text-sm text-gray-500">
                ⚡ Response time: {latencyMs}ms
              </div>
            )}
          </div>
        )}

        {/* Sources (non-query tabs only) - accordion */}
        {activeTab !== "query" && activeTab !== "explain-snippet" && sources.length > 0 && (
          <div className="space-y-4">
            <button
              onClick={() => setSourcesOpen(!sourcesOpen)}
              className="mt-2 cursor-pointer text-xs text-gray-500 hover:text-gray-300"
            >
              {sourcesOpen
                ? `▼ ${sources.length} source${sources.length !== 1 ? "s" : ""} retrieved · click to collapse`
                : `▶ ${sources.length} source${sources.length !== 1 ? "s" : ""} retrieved · click to expand`}
            </button>
            {sourcesOpen && sources.map((s, i) => (
              <div
                key={i}
                className="rounded-lg border border-gray-700 bg-gray-900/80 p-3"
              >
                <div className="mb-2 flex flex-wrap gap-2 items-center text-xs">
                  <span className="font-medium text-emerald-400 truncate" title={s.file}>
                    {s.file}
                  </span>
                  <span className="text-gray-400">{s.paragraph}</span>
                  <span className="text-gray-400">
                    {formatLineRange(s.start_line, s.end_line)}
                  </span>
                  {s.score != null && (
                    <span
                      className={`shrink-0 px-2 py-0.5 rounded-full font-medium ${
                        s.score >= 55 ? "bg-green-900 text-green-300" :
                        s.score >= 40 ? "bg-yellow-900 text-yellow-300" :
                        "bg-red-900 text-red-300"
                      }`}
                    >
                      {typeof s.score === "number" ? s.score.toFixed(1) : s.score}%
                    </span>
                  )}
                </div>
                <SyntaxHighlighter
                  language="cobol"
                  style={vscDarkPlus}
                  customStyle={{ borderRadius: "6px", fontSize: "12px" }}
                  PreTag="div"
                  codeTagProps={{ style: { fontFamily: "var(--font-geist-mono)" } }}
                >
                  {s.snippet}
                </SyntaxHighlighter>
                {(s.source || s.path) && (
                  <button
                    onClick={() => handleViewFullFile(s.source || s.path || "", i)}
                    className="mt-2 rounded border border-gray-600 bg-gray-800 px-2 py-1 text-xs text-gray-300 hover:bg-gray-700"
                  >
                    {expandedSourceIdx === i && expandedFile ? "Collapse" : "View full file"}
                  </button>
                )}
                {expandedSourceIdx === i && expandedFile && (
                  <div className="mt-3 rounded border border-gray-700 bg-gray-950 p-3">
                    <div className="mb-1 text-xs text-gray-400">
                      {expandedFile.path} ({expandedFile.line_count} lines)
                    </div>
                    <SyntaxHighlighter
                      language="cobol"
                      style={vscDarkPlus}
                      customStyle={{ borderRadius: "6px", fontSize: "12px", maxHeight: "300px" }}
                      PreTag="div"
                      showLineNumbers
                    >
                      {expandedFile.content}
                    </SyntaxHighlighter>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
        </div>
      </main>

    </div>
  );
}
